<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR20TfgY\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR20TfgY/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR20TfgY.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR20TfgY\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerR20TfgY\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'R20TfgY',
    'container.build_id' => '8f1b6569',
    'container.build_time' => 1615313887,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR20TfgY');
