<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU6uofrL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU6uofrL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU6uofrL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU6uofrL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerU6uofrL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'U6uofrL',
    'container.build_id' => 'dde02acb',
    'container.build_time' => 1616882621,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU6uofrL');
