<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGWesyaN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGWesyaN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGWesyaN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGWesyaN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGWesyaN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GWesyaN',
    'container.build_id' => 'f603e1ad',
    'container.build_time' => 1615311456,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGWesyaN');
